export default {
    LOAD_MESSAGE:"GET_MESSAGE",
    POST_MESSAGE:"POST_MESSAGE",
    UPDATE_MESSAGE:"UPDATE_MESSAGE",
    DELETE_MESSAGE:"DELETE_MESSAGE",
    FETCH_MESSAGE:"FETCH_MESSAGE",
    SET_PAGE:"SET_PAGE",
    UPDATE_ONLINE_LIST:"ONLINE_LIST"
}